version: "3.9"

services:
  event-seat-web:
    container_name: event-seat-web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80" # แก้จาก 80:80 เป็น 3000:80 (เข้าผ่าน localhost:3000)
    environment:
      - NEXT_PUBLIC_API_URL=https://api.event-seat.elitefund.fun/api
      - NODE_ENV=production
    env_file:
      - .env
    restart: always
    networks:
      - event-network

networks:
  event-network:
    driver: bridge
